# Generated by Django 4.2.1 on 2023-05-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petugas', '0003_alter_tabelpetugas_password'),
        ('pinjam', '0002_remove_tabelpinjams_judul_tabelpinjamn'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabelKembaliS',
            fields=[
                ('noKembaliS', models.AutoField(primary_key=True, serialize=False)),
                ('tglKembali', models.DateField()),
                ('tglPengembalian', models.DateField()),
                ('denda', models.IntegerField()),
                ('kodePetugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='petugas.tabelpetugas')),
                ('noPinjamS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.tabelpinjams')),
            ],
        ),
    ]
