# Generated by Django 4.2.1 on 2023-06-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petugas', '0003_alter_tabelpetugas_password'),
        ('pinjam', '0002_remove_tabelpinjams_judul_tabelpinjamn'),
        ('kembali', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabelKembaliN',
            fields=[
                ('noKembaliN', models.AutoField(primary_key=True, serialize=False)),
                ('tglKembali', models.DateField()),
                ('tglPengembalian', models.DateField()),
                ('denda', models.IntegerField()),
                ('kodePetugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='petugas.tabelpetugas')),
                ('noPinjamN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pinjam.tabelpinjamn')),
            ],
        ),
    ]
