# Generated by Django 4.2.1 on 2023-05-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petugas', '0003_alter_tabelpetugas_password'),
        ('anggota', '0004_tabelnon'),
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabelPinjamS',
            fields=[
                ('noPinjamS', models.AutoField(primary_key=True, serialize=False)),
                ('tglPinjam', models.DateField()),
                ('tglKembali', models.DateField()),
                ('judul', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField()),
                ('kodePetugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='petugas.tabelpetugas')),
                ('kodebuku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buku.tabelbuku')),
                ('no_anggota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anggota.tabelsiswa')),
            ],
        ),
    ]
