# Generated by Django 4.2.1 on 2023-05-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petugas', '0003_alter_tabelpetugas_password'),
        ('buku', '0001_initial'),
        ('anggota', '0004_tabelnon'),
        ('pinjam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelpinjams',
            name='judul',
        ),
        migrations.CreateModel(
            name='tabelPinjamN',
            fields=[
                ('noPinjamN', models.AutoField(primary_key=True, serialize=False)),
                ('tglPinjam', models.DateField()),
                ('tglKembali', models.DateField()),
                ('jumlah', models.IntegerField()),
                ('kodePetugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='petugas.tabelpetugas')),
                ('kodebuku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buku.tabelbuku')),
                ('no_anggotaN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anggota.tabelnon')),
            ],
        ),
    ]
