# Generated by Django 4.2.1 on 2023-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petugas', '0002_alter_tabelpetugas_kodepetugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelpetugas',
            name='password',
            field=models.CharField(max_length=35),
        ),
    ]
