# Generated by Django 4.2.1 on 2023-05-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggotasiswa',
            old_name='nim',
            new_name='nis',
        ),
    ]
