# Generated by Django 4.2.1 on 2023-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0003_rename_anggotasiswa_tabelsiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabelNon',
            fields=[
                ('no_anggotaN', models.AutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=50)),
                ('kode_post', models.CharField(max_length=20)),
                ('hp', models.CharField(max_length=20)),
            ],
        ),
    ]
