# Generated by Django 4.2.1 on 2023-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0004_tabelnon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelnon',
            name='nip',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='tabelsiswa',
            name='nis',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
