# Generated by Django 4.2.1 on 2023-05-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabelBuku',
            fields=[
                ('kodebuku', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=50)),
                ('pengarang', models.CharField(max_length=50)),
                ('thnterbit', models.CharField(max_length=4)),
                ('kotaterbit', models.CharField(max_length=20)),
                ('bahasa', models.CharField(max_length=20)),
                ('edisi', models.CharField(max_length=20)),
                ('deskripsi', models.CharField(max_length=50)),
            ],
        ),
    ]
